/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package semesterProject;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.HBox;
import javafx.stage.Stage;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        primaryStage.setScene(new Scene(new HBox(new Label("hello."))));
        primaryStage.show();
    }
}
